#!/usr/bin/env bash
# This scripts displays "Best School" 10 times, but display "Hi" before the tenth time.

i=1
while [ $i -lt 11 ]
do
	if [ $i = 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	(( i++ ))
done
