#!/usr/bin/env bash
# This scripts displays "Best School" 10 times, but display "Hi" before the tenth time.

COUNTER=0
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    let COUNTER+=1
done
